language: python
python:
  - "2.7"
sudo: required
dist: trusty

branches:
  only:
    - master
    - develop

services:
  - docker

env:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - ./.ci/docker-up.sh

script:
  - ./.ci/test.sh

# after_script:
#   - ./.ci/publish-ci.sh

notifications:
  email: false
